module.exports = function(grunt) {
  grunt.config.set("bower", {
    dev: {
      options: {
        layout: "byComponent",
        targetDir: './assets/bower',
        install: true,
        cleanTargetDir: true
      }
    },
    prod: {
      options: {
        layout: "byComponent",
        targetDir: './assets/bower',
        install: true,
        cleanTargetDir: true,
        cleanBowerDir: true
      }
    }
  });
  grunt.loadNpmTasks('grunt-bower-task');
};

// ---
// generated by coffee-script 1.9.2
