module.exports.passport = {
  local: {
    strategy: require('passport-local').Strategy
  },
  // facebook: {
  //   name: 'Facebook',
  //   protocol: 'oauth2',
  //   strategy: require('passport-facebook').Strategy,
  //   options: {
  //     clientID: '',
  //     clientSecret: '',
  //     scope: ['email']
  //   }
  // }
};

// ---
// generated by coffee-script 1.9.2
